use_default_settings: true

server:
  port: 8080
  bind_address: "0.0.0.0"
  limiter: false

search:
  safe_search: 0
  autocomplete: "duckduckgo"
  default_lang: "en"
  formats:
    - html
    - json

redis:
  url: "redis://valkey:6379"
